export const DISPLAY_PRODUCTS_ALL = "DISPLAY_PRODUCT_ALL";
export const DISPLAY_PRODUCT_ONE = "DISPLAY_PRODUCT_ONE";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const LOADING_PRODUCT = "LOADING_PRODUCT";